### ISSUE TITLE
Information: Arch Linux package available.

### ISSUE THREAD

**Issue by dreirund** [Cryolitia/gpd-fan-driver#1]
Informational:  
There is now an Arch Linux package of this available: [`gpd-fan-driver-dkms-git`](https://aur.archlinux.org/packages/gpd-fan-driver-dkms-git).

If you want, you can link it in your [`README.md`](https://github.com/Cryolitia/gpd-fan-driver/blob/main/README.md).

Regards and many thanks for the module!

**Comment by Cryolitia** [comment]
done in https://github.com/Cryolitia/gpd-fan-driver/commit/724b51e1a0deda4225d8c93019d545da41aa4b9a

thx

**Comment by Cryolitia** [comment]
Hello, sorry for bother you again after a long time. If you would like to test the driver and report it if it works fine on your device in https://github.com/Cryolitia/gpd-fan-driver/issues/12( or open a new issue if any problem),  I would be appreciate it. It will help me a lot in maintaining and upstreaming it.

**Comment by dreirund** [comment]
> *Hello, sorry for bother you again after a long time. If you would like to test the driver and report it if it works fine on your device in [#12](https://github.com/Cryolitia/gpd-fan-driver/issues/12) or open a new issue if any problem), I would be appreciate it. It will help me a lot in maintaining and upstreaming it.*

Like [this](https://github.com/Cryolitia/gpd-fan-driver/issues/12#issuecomment-2708899838)?

**Comment by Cryolitia** [comment]
> Like [this](https://github.com/Cryolitia/gpd-fan-driver/issues/12#issuecomment-2708899838)?

Yes. Thx again
