### ISSUE TITLE
[Enhancement suggestion] Make `pwm1` return the firmware-set value in auto mode.

### ISSUE THREAD

**Issue by dreirund** [Cryolitia/gpd-fan-driver#3]
Many thanks again for your module!

An enhancement suggestion:

If `pwm1_enable` is `2` (auto), then I suggest that a read from `pwm1` returns the current setting applied by firmware.

Regards!

**Comment by Cryolitia** [comment]
I have just submitted a commit https://github.com/Cryolitia/gpd-fan-driver/commit/07c7f0c05c058cd0f7f733de4dc483e4b7175147 to directly access ECRAM in debugfs. You could use it by enable debugfs in your kernel, and do sth. like `sudo cat /sys/kernel/debug/gpdfan/pwm_reg` .

Although it's feasible for WinMax2-like devices to read the auto pwm value, but for WinMini-like devices, I suspect it's always `0` under auto mode.

I would consider to implement it for WinMax2-like devices if your test is OK.

**Comment by dreirund** [comment]
> You could use it by enable debugfs in your kernel, and do sth. like `sudo cat /sys/kernel/debug/gpdfan/pwm_reg`

It seems to work (GPD Win Max 2 2023).  
When I manually set the speed, I see that `/sys/kernel/debug/gpdfan/pwm_reg`=`184` corresponds to max speed (`255` in the hwmon control file), while `/sys/kernel/debug/gpdfan/pwm_reg`=`1` corresponds to min speed (`0` in the hwmon control file), so translation seems not be straig forward.

`/sys/kernel/debug/gpdfan/manual_control_reg` is `1` when in manual or in max speed mode (hwmon interface `pwm1_enable`=`0` or `1`), and `0` when in auto mode (hwmon interface `pwm1_enable`=`2`).

**Comment by Cryolitia** [comment]
> > You could use it by enable debugfs in your kernel, and do sth. like `sudo cat /sys/kernel/debug/gpdfan/pwm_reg`
> 
> It seems to work (GPD Win Max 2 2023). When I manually set the speed, I see that `/sys/kernel/debug/gpdfan/pwm_reg`=`184` corresponds to max speed (`255` in the hwmon control file), while `/sys/kernel/debug/gpdfan/pwm_reg`=`1` corresponds to min speed (`0` in the hwmon control file), so translation seems not be straig forward.
> 
> `/sys/kernel/debug/gpdfan/manual_control_reg` is `1` when in manual or in max speed mode (hwmon interface `pwm1_enable`=`0` or `1`), and `0` when in auto mode (hwmon interface `pwm1_enable`=`2`).

translation here: https://github.com/Cryolitia/gpd-fan-driver/blob/7df66555dea2e035fb58275059ab94945f6ebdad/gpd-fan.c#L145 , and `pwm_max` is in the datasheet in README.md .

**Comment by Cryolitia** [comment]
A warning is that, once that you set `pwm_reg` a number bigger that `pwm_max`, the fan will just stop work.
