### ISSUE TITLE
Made an `gpdfanspeed` command line control utility.

### ISSUE THREAD

**Issue by dreirund** [Cryolitia/gpd-fan-driver#5]
I made a simple bash programme that interferes with this driver and allows to print or set settings.

Feel free to bundle it as utility with your driver:  
[`gpdfanspeed`](https://aur.archlinux.org/cgit/aur.git/plain/gpdfanspeed?h=gpd-fan-driver-dkms-git)

**Comment by Cryolitia** [comment]
I don't think there's a need for a bash utility wrapper again for a driver that fully adheres to the linux hwmon subsystem, userspace programs can use libsensor or whatever implementation they like. Anyway, thanks for your labor, I'll mention this in the README later.

**Comment by dreirund** [comment]
> *I don't think there's a need for a bash utility wrapper again for a driver that fully adheres to the linux hwmon subsystem*

OK, I never dealt with the hwmon subsystem before and when I wrote the utility I thought the driver needs machine-specific usage on the user interface side.

But now I got it, that the driver exposes a standardised interface to userspace.
