### ISSUE TITLE
GPD Win Mini: Auto turns the fan off, instead of the default fan curve

### ISSUE THREAD

**Issue by justinweiss** [Cryolitia/gpd-fan-driver#9]
On the GPD Win Mini, setting pwm1_enable to 2 (automatic) will turn the fan off instead of setting it to auto.

The Win Mini uses a fan speed of "0" to indicate automatic, but this line will convert "0" to "1", which means "fan off": https://github.com/Cryolitia/gpd-fan-driver/blob/main/gpd-fan.c#L164

I think this calculation should be bypassed or fixed to 0 when the input is 0.

**Comment by Cryolitia** [comment]
Sorry about it, I will fix it as soon as possible

**Comment by Cryolitia** [comment]
I'm so glad that you would like to try it on Win Mini, I have never found a tester on the device before. 

Could I please request you to test it entirely on Win Mini.

Would you like to credit yourself by appending a line like `Tested-by: name <email>` when I upstreaming it?

**Comment by justinweiss** [comment]
Thanks! That fixed it. I tested auto and manual, and writing some different values to pwm1 and it all seems to work out OK. It also works with hhfc for setting curves. So it seems to work fine now! I can send a Tested-by line when you upstream it, definitely.

One problem with hhfc is that it resets pwm1_enable to 0 when it exits, which sets the fan to full speed. It seems like other tools also treat `0` as "default" rather than "full speed," and that's also how the upstreamed oxp-sensors driver works, with 2+ used for additional curves defined in bios or hardware.

I know the documentation says `0: no fan speed control (i.e. fan at full speed)`, but it seems like there's a lot of precedent for that meaning "release control of the fan to the hardware" rather than "set to manual / full speed" among existing hardware and tools.

**Comment by Cryolitia** [comment]
I think the function of enable=0 can be set by parameter on probing, I'll finish it soon.

**Comment by Cryolitia** [comment]
> I know the documentation says `0: no fan speed control (i.e. fan at full speed)`, but it seems like there's a lot of precedent for that meaning "release control of the fan to the hardware" rather than "set to manual / full speed" among existing hardware and tools.

It's now discussed: https://lore.kernel.org/lkml/528fed98-4fe0-41b6-b148-cf950866cdb3@roeck-us.net/T/
My implementation is the only correct behavior.
